services:
  - type: web
    name: elogrind-api
    env: node
    buildCommand: npm ci && npm run db:generate && npm run build
    startCommand: npm run db:migrate && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: elogrind-api
          envVarKey: PORT
      - key: DATABASE_URL
        sync: false
      - key: MERCADO_PAGO_ACCESS_TOKEN
        sync: false
      - key: MERCADO_PAGO_PUBLIC_KEY
        sync: false
      - key: MERCADO_PAGO_WEBHOOK_URL
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "https://elogrind.gg,https://admin.elogrind.gg"
      - key: RATE_LIMIT_WINDOW_MS
        value: 60000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: TRUST_PROXY
        value: 1

databases:
  - name: elogrind-db
    databaseName: elogrind
    user: elogrind
